---
services:
  db:
    image: postgres:17
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: songs
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d songs"]
      interval: 1s
      timeout: 5s
      retries: 5
