from pydantic import BaseModel, Field


class GenAIRequest(BaseModel):
    user_prompt: str = Field(description="The user's prompt to the AI model")


class GenAIResponse(BaseModel):
    response: str = Field(description="The response generated by the AI model")
