from pydantic import BaseModel, Field


class APIRequest(BaseModel):
    curl_cmd: str = Field(description="The cURL command version of the request")


class GenerateQueryRequest(BaseModel):
    user_prompt: str = Field(description="The user's prompt to the AI model")


class GenerateQueryResponse(BaseModel):
    generated_request: APIRequest = Field(
        description="The request generated by the AI model"
    )
